[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[functions."generate-site"]
  timeout = 60

[dev]
  command = "npm run dev:vite"
  port = 8888
  targetPort = 5173
