import type { BusinessDetails, GeneratedSite } from "../types";

interface Props {
  business: BusinessDetails;
  site: GeneratedSite;
}

export function SitePreview({ business, site }: Props) {
  function download() {
    const blob = new Blob([site.html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const slug = business.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    a.href = url;
    a.download = `${slug || "site"}.html`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  function openInNewTab() {
    const blob = new Blob([site.html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    window.open(url, "_blank", "noopener");
  }

  const mapUrl = business.google_maps_uri
    || `https://www.google.com/maps/place/?q=place_id:${encodeURIComponent(business.place_id)}`;

  return (
    <div className="preview-wrap">
      <div className="preview-meta">
        <h3>{business.name}</h3>
        <div className="muted">{business.formatted_address || business.address}</div>

        <div>
          <span className={"lead-score " + (business.lead_score >= 8 ? "" : business.lead_score >= 5 ? "mid" : "low")}>
            Lead score {business.lead_score}/10
          </span>
        </div>

        <div style={{ marginTop: 12 }}>
          <div className="meta-row">
            <span className="lbl">Rating</span>
            <span>{business.rating ? `★ ${business.rating.toFixed(1)} (${business.user_ratings_total ?? 0})` : "—"}</span>
          </div>
          <div className="meta-row">
            <span className="lbl">Mobiles</span>
            <span>{business.phones.mobiles.join(", ") || "—"}</span>
          </div>
          <div className="meta-row">
            <span className="lbl">Landlines</span>
            <span>{business.phones.landlines.join(", ") || "—"}</span>
          </div>
          <div className="meta-row">
            <span className="lbl">Photos</span>
            <span>{business.photo_refs.length}</span>
          </div>
          <div className="meta-row">
            <span className="lbl">Generated by</span>
            <span>{site.model || site.provider || site.generated_by}</span>
          </div>
        </div>

        {site.suggested_pages && site.suggested_pages.length > 0 && (
          <div style={{ marginTop: 12 }}>
            <div className="lbl" style={{ fontSize: 11, textTransform: "uppercase", color: "var(--text-muted)" }}>
              Suggested pages
            </div>
            <div className="kw-list">
              {site.suggested_pages.map((p) => (
                <span key={p} className="badge">{p}</span>
              ))}
            </div>
          </div>
        )}

        <div style={{ marginTop: 10 }}>
          <div className="lbl" style={{ fontSize: 11, textTransform: "uppercase", color: "var(--text-muted)" }}>
            SEO keywords
          </div>
          <div className="kw-list">
            {site.seo_keywords.map((k) => (
              <span key={k} className="badge green">{k}</span>
            ))}
          </div>
        </div>

        <div className="preview-actions">
          <button className="btn btn-sm" onClick={download}>Download HTML</button>
          <button className="btn btn-sm btn-secondary" onClick={openInNewTab}>Open in tab</button>
          <a className="btn btn-sm btn-secondary" href={mapUrl} target="_blank" rel="noopener">Maps</a>
        </div>
      </div>

      <div>
        <iframe
          className="preview-iframe"
          title={`${business.name} preview`}
          srcDoc={site.html}
          // allow-scripts: needed for any JS the LLM emits (mobile menu,
          //   intersection observers, smooth scroll, gallery sliders, etc.).
          // allow-same-origin: keeps localStorage / fetch from the iframe
          //   working — generated sites occasionally rely on it.
          // Combination is a stated MDN risk, but the content is our own
          //   model output rendered into our own preview UI; not a
          //   third-party embed.
          sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"
          referrerPolicy="no-referrer"
        />
      </div>
    </div>
  );
}
